### ISSUE TITLE
Saving an answer after adding a reference

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#213]
When I answer a question and then add a reference before saving my answer, both the score and justification box look blank, as if I haven't answered yet. This also happened last week.

**Comment by ahasemann** [comment]
This is being addressed in #193

**Comment by byndcivilization** [comment]
@ahasemann @gjacovella Can i get confirmation that this was addressed in this mornings push?

**Comment by ahasemann** [comment]
Yes, works now

**Comment by gjacovella** [comment]
@byndcivilization @ahasemann no, I still have this problem. (I'm working as a peer reviewer on the Italy pilot assessment)

**Comment by DianaHartmann** [comment]
I have the same issue. Im working as a researcher (ahasermann) on Uruguay assessment.

**Comment by HumairaP** [comment]
I had the same problem with adding a document, however when I added an interview it was okay.

**Comment by HumairaP** [comment]
@byndcivilization

**Comment by ahasemann** [comment]
Yes, same for me, interview is fine, but doesn't work with doc upload

**Comment by DianaHartmann** [comment]
I had the same issue when I added a document as a first reference. Score and justification disappeared.

**Comment by byndcivilization** [comment]
Browser?

**Comment by HumairaP** [comment]
google chrome for me

**Comment by DianaHartmann** [comment]
Same for me, chrome

**Comment by byndcivilization** [comment]
Found it. Will be addressed on the next push
